apiVersion: v1
kind: Service
metadata:
  name: gravity-operator-admin
  labels:
    app.kubernetes.io/name: gravity-operator-admin
    helm.sh/chart: gravity-operator-0.3.0
    app.kubernetes.io/instance: gravity-operator-admin
    app.kubernetes.io/managed-by: Tiller
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30066
  selector:
    app.kubernetes.io/name: gravity-operator-admin
    app.kubernetes.io/instance:  gravity-operator-admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gravity-operator-admin
  labels:
    app.kubernetes.io/name: gravity-operator-admin
    helm.sh/chart: gravity-operator-0.3.0
    app.kubernetes.io/instance: gravity-operator-admin
    app.kubernetes.io/managed-by: Tiller
data:
  gravity.conf: |
    tcp_nopush          on;
    tcp_nodelay         on;
    types_hash_max_size 2048;

    gzip on;
    gzip_min_length 1024;
    gzip_buffers 4 8k;
    gzip_types text/plain application/x-javascript text/css application/xml application/json;

    server {
      listen       80;
      server_name  localhost;

      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api/ {
        proxy_pass http://gravity-operator:80/;
      }

      location /health {
              access_log off;
              return 200 "healthy";
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gravity-operator-admin
  labels:
    app.kubernetes.io/name: gravity-operator-admin
    helm.sh/chart: gravity-operator-0.3.0
    app.kubernetes.io/instance: gravity-operator-admin
    app.kubernetes.io/managed-by: Tiller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gravity-operator-admin
      app.kubernetes.io/instance: gravity-operator-admin
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gravity-operator-admin
        app.kubernetes.io/instance: gravity-operator-admin
    spec:
      restartPolicy: Always
      volumes:
        - name: ng-conf
          configMap:
            name: gravity-operator-admin
      containers:
        - name: admin
          image: "moiot/gravity-admin:v0.2.0"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: ng-conf
              mountPath: /etc/nginx/conf.d
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
