apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install

  name: clusters.gravity.mobike.io

spec:
  conversion:
    strategy: None
  group: gravity.mobike.io
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Total number of pipelines.
          jsonPath: .status.pipelines
          name: Total
          type: integer
        - description: Total number of pipelines which version match current deployment
            rule.
          jsonPath: .status.updatedPipelines
          name: Updated
          type: integer
        - description: Total number of available pipelines (ready for at least minReadySeconds).
          jsonPath: .status.availablePipelines
          name: Available
          type: integer
        - description: Total number of unavailable pipelines.
          jsonPath: .status.unavailablePipelines
          name: Unavailable
          type: integer
      name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deploymentRules:
                  type: array
                  items:
                    type: object
                    properties:
                      command:
                        type: array
                        items:
                          type: string
                      group:
                        type: string
                      image:
                        type: string
                      pipelines:
                        type: array
                        items:
                          type: string
                rolling:
                  type: string

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  generation: 1
  name: pipelines.gravity.mobike.io

spec:
  conversion:
    strategy: None
  group: gravity.mobike.io
  names:
    kind: Pipeline
    listKind: PipelineList
    plural: pipelines
    singular: pipeline
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Position of the pipeline.
          jsonPath: .status.position
          name: Position
          type: string
      name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                command:
                  type: array
                  items:
                    type: string
                configHash:
                  type: string
                image:
                  type: string
                lastUpdate:
                  type: string
                  format: date-time
                paused:
                  type: boolean
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                command:
                  type: array
                  items:
                    type: string
                image:
                  type: string
                podName:
                  type: string
                position:
                  type: string
              x-kubernetes-preserve-unknown-fields: true