---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gravity-operator-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["gravity.mobike.io"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gravity-operator-rolebinding
subjects:
  - kind: ServiceAccount
    name: gravity-operator
roleRef:
  kind: Role
  name: gravity-operator-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gravity-operator
